Jeweler -> Bundler. Fixes #6
Jeweler does lots of stuff that is really bad, and Bundler's tasks are
actually quite lightweight. So I ported all the infrastructure over to
Bundler.

```
$ bundle
$ bundle exec rake test
$ bundle exec rake install
$ irb
irb(main):001:0> require 'dude'
=> true
irb(main):002:0> Exception.new
ArgumentError: wrong number of arguments (0 for 1), dude.
```

:metal: